/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import javax.swing.SwingUtilities;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author sourabhkumar
 */
public class GraphPlotter extends javax.swing.JFrame {

    public GraphPlotter(String title) {
        super(title);
        
        // Create a dataset
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        // Populate the dataset with your data
        dataset.addValue(1000.0, "Revenue", "Course 1");
        dataset.addValue(1500.0, "Revenue", "Course 2");
        dataset.addValue(800.0, "Revenue", "Course 3");
        
        // Create the chart
        JFreeChart barChart = ChartFactory.createBarChart(
            "Course Revenue",
            "Course",
            "Revenue",
            dataset,
            PlotOrientation.VERTICAL,
            true,
            true,
            false
        );

        // Create a JPanel to hold the chart
        JPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        
        // Add the chart panel to the JFrame
        setContentPane(chartPanel);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
   
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
            GraphPlotter chartFrame = new GraphPlotter("Course Revenue Chart");
            chartFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            chartFrame.pack();
            chartFrame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
