/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.DonationCentreInterface.DonarLoginPages.DonarBankProfileLoginPages;
import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.Enterprise.DonationCentre.UserDonor;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectUserInterface.MainJFrameForm;
import java.awt.Color;
import javax.swing.BorderFactory;
/**
 *
 * @author sourabh
 */
  


public class DonarProfileDetails extends javax.swing.JPanel {

    /**
     * Creates new form DonarProfileDetails
     */
    
    boolean ValidationStatus = true;
    boolean validationCheck = true;
    
    MainJFrameForm MainLPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    UserDonor donar;
    
    public DonarProfileDetails(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem, UserDonor don) {
        initComponents();
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        this.donar = don;
        
        
        name_txt.setText(don.getNamePerson());
        uname_txt.setText(don.getpName());
        add_txt.setText(don.getAddr());
        phone_txt.setText(don.getContactNumber());
        dob_txt.setText(don.getDob().toString());
        bank_txt.setText(don.getBankDonorName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donardetails = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        unmae_lbl = new javax.swing.JLabel();
        uname_txt = new javax.swing.JTextField();
        add_lbl = new javax.swing.JLabel();
        add_txt = new javax.swing.JTextField();
        con_lbl = new javax.swing.JLabel();
        phone_txt = new javax.swing.JTextField();
        dob_lbl = new javax.swing.JLabel();
        dob_txt = new javax.swing.JTextField();
        bank_lbl = new javax.swing.JLabel();
        bank_txt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(169, 146, 125));

        donardetails.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        donardetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        donardetails.setText("Donor Details");

        name_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_lbl.setText("Name:");

        name_txt.setEditable(false);

        unmae_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unmae_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unmae_lbl.setText("Username:");

        uname_txt.setEditable(false);
        uname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname_txtActionPerformed(evt);
            }
        });

        add_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_lbl.setText("Address:");

        add_txt.setEditable(false);

        con_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        con_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        con_lbl.setText("Phone no.:");

        phone_txt.setEditable(false);
        phone_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_txtActionPerformed(evt);
            }
        });
        phone_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phone_txtKeyReleased(evt);
            }
        });

        dob_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dob_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dob_lbl.setText("Date of Birth:");

        dob_txt.setEditable(false);
        dob_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob_txtActionPerformed(evt);
            }
        });
        dob_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dob_txtKeyReleased(evt);
            }
        });

        bank_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bank_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bank_lbl.setText("Donor Bank:");

        bank_txt.setEditable(false);
        bank_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bank_txtActionPerformed(evt);
            }
        });
        bank_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bank_txtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(donardetails, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dob_lbl)
                                    .addComponent(bank_lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bank_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(con_lbl)
                                .addGap(30, 30, 30)
                                .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(add_lbl)
                                    .addComponent(unmae_lbl)
                                    .addComponent(name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(325, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {add_txt, bank_txt, dob_txt, name_txt, phone_txt, uname_txt});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {add_lbl, bank_lbl, con_lbl, dob_lbl, name_lbl, unmae_lbl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(donardetails, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unmae_lbl))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(con_lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob_lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bank_lbl)
                    .addComponent(bank_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {add_lbl, add_txt, bank_lbl, bank_txt, con_lbl, dob_lbl, dob_txt, name_lbl, name_txt, phone_txt, uname_txt, unmae_lbl});

    }// </editor-fold>//GEN-END:initComponents

    private void phone_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_txtActionPerformed

    private void phone_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_txtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_txtKeyReleased

    private void dob_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_txtActionPerformed

    private void dob_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dob_txtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_txtKeyReleased

    private void bank_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bank_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bank_txtActionPerformed

    private void bank_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bank_txtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_bank_txtKeyReleased

    private void uname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uname_txtActionPerformed

    private boolean RegexValidation() {
    if(!name_txt.getText().matches("^[a-zA-Z ]+$"))
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(!phone_txt.getText().matches("^[0-9]{10}$"))
        {
            phone_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            phone_txt.setToolTipText("Please enter a 10 digit number");
            validationCheck=false;
        }


 

        return validationCheck;


    }   


    private boolean EmpytyFieldValidation() {

        if(name_txt.getText().equals(null) || name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!name_txt.getText().equals(null) && !name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(uname_txt.getText().equals(null) || uname_txt.getText().trim().isEmpty() )
            {
                uname_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                uname_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatus= false;
            }
        if(!uname_txt.getText().equals(null) && !uname_txt.getText().trim().isEmpty() )
        {
            uname_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(add_txt.getText().equals(null) || add_txt.getText().trim().isEmpty() )
        {
            add_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            add_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!add_txt.getText().equals(null) && !add_txt.getText().trim().isEmpty() )
        {
            add_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(phone_txt.getText().equals(null) || phone_txt.getText().trim().isEmpty() )
        {
            phone_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            phone_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!phone_txt.getText().equals(null) && !phone_txt.getText().trim().isEmpty() )
        {
            phone_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        
        if(dob_txt.getText().equals(null) || dob_txt.getText().trim().isEmpty() )
        {
            dob_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            dob_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!dob_txt.getText().equals(null) && !dob_txt.getText().trim().isEmpty() )
        {
            dob_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(bank_txt.getText().equals(null) || bank_txt.getText().trim().isEmpty() )
        {
            bank_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            bank_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!bank_txt.getText().equals(null) && !bank_txt.getText().trim().isEmpty() )
        {
            bank_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

     
        
        return ValidationStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_lbl;
    private javax.swing.JTextField add_txt;
    private javax.swing.JLabel bank_lbl;
    private javax.swing.JTextField bank_txt;
    private javax.swing.JLabel con_lbl;
    private javax.swing.JLabel dob_lbl;
    private javax.swing.JTextField dob_txt;
    private javax.swing.JLabel donardetails;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JTextField uname_txt;
    private javax.swing.JLabel unmae_lbl;
    // End of variables declaration//GEN-END:variables
}
