/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.NGOInterface;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.NGO.NGOClass;
import finalprojectBackend.Enterprise.NGO.Caretaker;
import finalprojectUserInterface.MainJFrameForm;
import java.awt.Color;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author sourabh
 */
public class CaretakerSignUp extends javax.swing.JPanel {

    /**
     * Creates new form CaretakerSignUp
     */
    Random rand = new Random();
    
    boolean emptyValidationStatus = true;
    boolean validationCheck = true;
    
    
    MainJFrameForm MainLoginPage;
    //FirebaseHelper firebaseHelper;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    public CaretakerSignUp(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLoginPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        for(NGOClass h: operatingSystem.getNGODirectory().getListOfNGO()){
            ngo_list.addItem(h.getNameEnterprise());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_admintitle = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        name_lbl = new javax.swing.JLabel();
        uname_lbl = new javax.swing.JLabel();
        pswd_lbl = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contact_lbl = new javax.swing.JLabel();
        Contact_txt = new javax.swing.JTextField();
        dob_txt = new javax.swing.JTextField();
        gen_cmb = new javax.swing.JComboBox<>();
        pwd_txt = new javax.swing.JPasswordField();
        uname_txt = new javax.swing.JTextField();
        ngo_list = new javax.swing.JComboBox<>();
        reg_txt = new javax.swing.JTextField();
        lbl_ngo = new javax.swing.JLabel();
        lbl_reg = new javax.swing.JLabel();
        address_lbl = new javax.swing.JLabel();
        add_txt = new javax.swing.JTextField();
        city_txt = new javax.swing.JTextField();
        City_txt = new javax.swing.JLabel();
        state_txt = new javax.swing.JLabel();
        txt_state = new javax.swing.JTextField();
        zip_txt = new javax.swing.JTextField();
        zip_lbl = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        signup_btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(181, 189, 174));

        lbl_admintitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_admintitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_admintitle.setText("Create Caretaker Profile");

        name_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_lbl.setText("Name:");

        uname_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        uname_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uname_lbl.setText("Username:");

        pswd_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pswd_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pswd_lbl.setText("Password:");

        gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender.setText("Gender:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DOB:");

        contact_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        contact_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact_lbl.setText("Contact:");

        gen_cmb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gen_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        ngo_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        lbl_ngo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ngo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ngo.setText("NGO:");

        lbl_reg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_reg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_reg.setText("Registered No.:");

        address_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        address_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        address_lbl.setText("Address:");

        City_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        City_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        City_txt.setText("City:");

        state_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        state_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        state_txt.setText("State:");

        zip_lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        zip_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zip_lbl.setText("Zip Code:");

        back_btn.setBackground(new java.awt.Color(255, 204, 51));
        back_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        signup_btn.setBackground(new java.awt.Color(255, 204, 51));
        signup_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signup_btn.setText("Sign Up");
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uname_lbl)
                    .addComponent(name_lbl)
                    .addComponent(pswd_lbl)
                    .addComponent(gender)
                    .addComponent(jLabel2)
                    .addComponent(contact_lbl))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Contact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pwd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gen_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ngo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state_txt)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_reg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(City_txt, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(zip_lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reg_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngo_list, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(zip_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238)
                .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_admintitle, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(404, 404, 404))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {City_txt, address_lbl, contact_lbl, gender, jLabel2, lbl_ngo, lbl_reg, name_lbl, pswd_lbl, state_txt, uname_lbl, zip_lbl});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Contact_txt, add_txt, city_txt, dob_txt, gen_cmb, name_txt, ngo_list, pwd_txt, reg_txt, txt_state, uname_txt, zip_txt});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {back_btn, signup_btn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(lbl_admintitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ngo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngo_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(address_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(City_txt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(state_txt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zip_lbl))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reg_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(add_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(city_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zip_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(name_lbl))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(uname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uname_lbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pwd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(pswd_lbl)
                                        .addGap(11, 11, 11)))
                                .addComponent(gen_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(gender)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Contact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact_lbl))))
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn)
                    .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {City_txt, Contact_txt, add_txt, address_lbl, city_txt, contact_lbl, dob_txt, gen_cmb, gender, jLabel2, lbl_ngo, lbl_reg, name_lbl, name_txt, ngo_list, pswd_lbl, pwd_txt, reg_txt, state_txt, txt_state, uname_lbl, uname_txt, zip_lbl, zip_txt});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {back_btn, signup_btn});

    }// </editor-fold>//GEN-END:initComponents

    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        // TODO add your handling code here:
        try {
            if(EmpytyFieldValidation())
            {
                if(RegexValidation())
                {
                    String address = add_txt.getText() + "," + city_txt.getText() + "," + txt_state.getText() + "," + zip_txt.getText();
                    int id = rand.nextInt(99);
                    //Nurse nurse = new Caretaker(txtFullName.getText(), txtNo.getText(), address, txtUsrName.getText(), txtPass.getText(), txtGender.getText(), txtDOB.getText(), new Date(),jComboBox1.getSelectedItem().toString());
                    Caretaker nurse = new Caretaker(uname_txt.getText(), pwd_txt.getText(), String.valueOf(id), name_txt.getText(), address, gen_cmb.getSelectedItem().toString(), reg_txt.getText(), new Date(), ngo_list.getSelectedItem().toString());

                    operatingSystem.addCaretaker(nurse);
                    dB4OUtility.storeSystem(operatingSystem);

                    MainJFrameForm suc = new MainJFrameForm();
                    ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
                    suc.setVisible(true);
                }
                else
                    {
                        JOptionPane.showMessageDialog(this,"Some Error in entered data.Please check over the red fields to know more.");
                        validationCheck=true;
                    }
            }
            else{
                    JOptionPane.showMessageDialog(this,"Data Cant be empty. Please check over the red fields to know more.");
                    emptyValidationStatus=true;
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Patient not registered, Try again");
             emptyValidationStatus=true;
        }
        
    }//GEN-LAST:event_signup_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:

        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    
    private boolean RegexValidation() {
    if(!name_txt.getText().matches("^[a-zA-Z ]+$"))
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(!Contact_txt.getText().matches("^[0-9]{10}$"))
        {
            Contact_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            Contact_txt.setToolTipText("Please enter a 10 digit number");
            validationCheck=false;
        }


        if(!zip_txt.getText().matches("^[0-9]{5}$"))
        {
            zip_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            zip_txt.setToolTipText("Please enter a 5 digit number");
            validationCheck=false;
        }

        if(!reg_txt.getText().matches("^[0-9]{10}$"))
        {
            reg_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            reg_txt.setToolTipText("Please enter a 10 digit number");
            validationCheck=false;
        }

        return validationCheck;


    }   


    private boolean EmpytyFieldValidation() {
        if(add_txt.getText().equals(null) || add_txt.getText().trim().isEmpty() )
        {
            add_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            add_txt.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!add_txt.getText().equals(null) && !add_txt.getText().trim().isEmpty() )
        {
            add_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(city_txt.getText().equals(null) || city_txt.getText().trim().isEmpty() )
        {
            city_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            city_txt.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!city_txt.getText().equals(null) && !city_txt.getText().trim().isEmpty() )
        {
            city_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(name_txt.getText().equals(null) || name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!name_txt.getText().equals(null) && !name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(pwd_txt.getText().equals(null) || pwd_txt.getText().trim().isEmpty() )
        {
            pwd_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            pwd_txt.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!pwd_txt.getText().equals(null) && !pwd_txt.getText().trim().isEmpty() )
        {
            pwd_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txt_state.getText().equals(null) || txt_state.getText().trim().isEmpty() )
        {
            txt_state.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            txt_state.setToolTipText("This Field Cannot be empty");
            emptyValidationStatus= false;
        }
        if(!txt_state.getText().equals(null) && !txt_state.getText().trim().isEmpty() )
        {
            txt_state.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(uname_txt.getText().equals(null) || uname_txt.getText().trim().isEmpty() )
            {
                uname_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                uname_txt.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!uname_txt.getText().equals(null) && !uname_txt.getText().trim().isEmpty() )
        {
            uname_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(zip_txt.getText().equals(null) || zip_txt.getText().trim().isEmpty() )
            {
                zip_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                zip_txt.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!zip_txt.getText().equals(null) && !zip_txt.getText().trim().isEmpty() )
        {
            zip_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(reg_txt.getText().equals(null) || reg_txt.getText().trim().isEmpty() )
            {
                reg_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                reg_txt.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!reg_txt.getText().equals(null) && !reg_txt.getText().trim().isEmpty() )
        {
            reg_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(Contact_txt.getText().equals(null) || Contact_txt.getText().trim().isEmpty() )
            {
                Contact_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                Contact_txt.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!Contact_txt.getText().equals(null) && !Contact_txt.getText().trim().isEmpty() )
        {
            Contact_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }
        
//        if(gender_txt.getText().equals(null) || gender_txt.getText().trim().isEmpty() )
//            {
//                gender_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
//                gender_txt.setToolTipText("This Field Cannot be empty");
//                emptyValidationStatus= false;
//            }
//        if(!gender_txt.getText().equals(null) && !gender_txt.getText().trim().isEmpty() )
//        {
//            gender_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
//        }
        
        if(dob_txt.getText().equals(null) || dob_txt.getText().trim().isEmpty() )
            {
                dob_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                dob_txt.setToolTipText("This Field Cannot be empty");
                emptyValidationStatus= false;
            }
        if(!dob_txt.getText().equals(null) && !dob_txt.getText().trim().isEmpty() )
        {
            dob_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }
        
        return emptyValidationStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel City_txt;
    private javax.swing.JTextField Contact_txt;
    private javax.swing.JTextField add_txt;
    private javax.swing.JLabel address_lbl;
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField city_txt;
    private javax.swing.JLabel contact_lbl;
    private javax.swing.JTextField dob_txt;
    private javax.swing.JComboBox<String> gen_cmb;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_admintitle;
    private javax.swing.JLabel lbl_ngo;
    private javax.swing.JLabel lbl_reg;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField name_txt;
    private javax.swing.JComboBox<String> ngo_list;
    private javax.swing.JLabel pswd_lbl;
    private javax.swing.JPasswordField pwd_txt;
    private javax.swing.JTextField reg_txt;
    private javax.swing.JButton signup_btn;
    private javax.swing.JLabel state_txt;
    private javax.swing.JTextField txt_state;
    private javax.swing.JLabel uname_lbl;
    private javax.swing.JTextField uname_txt;
    private javax.swing.JLabel zip_lbl;
    private javax.swing.JTextField zip_txt;
    // End of variables declaration//GEN-END:variables
}
