/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.NGOInterface;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.NGO.NGOClass;
import finalprojectBackend.Enterprise.NGO.Manager;
import finalprojectUserInterface.MainJFrameForm;
import java.awt.Color;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author sourabh
 */
public class ManagerSignUp extends javax.swing.JPanel {

    /**
     * Creates new form ManagerSignUp
     */
    
    Random random = new Random();
    long docnumber = random.nextInt(900000000) + 100000000;
    
    boolean ValidationStatus = true;
    boolean validationCheck = true;
    
    MainJFrameForm MainLoginPage;
    //FirebaseHelper firebaseHelper;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    public ManagerSignUp(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLoginPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        for(NGOClass h: operatingSystem.getNGODirectory().getListOfNGO()){
            ngolist.addItem(h.getNameEnterprise());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_admintitle = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        uname_lbl = new javax.swing.JLabel();
        uname_txt = new javax.swing.JTextField();
        pwd_lbl = new javax.swing.JLabel();
        pass_txt = new javax.swing.JPasswordField();
        ngo_lbl = new javax.swing.JLabel();
        ngolist = new javax.swing.JComboBox<>();
        depart_lbl = new javax.swing.JLabel();
        depart_txt = new javax.swing.JTextField();
        add_txt = new javax.swing.JTextField();
        address_lbl = new javax.swing.JLabel();
        city_txt = new javax.swing.JTextField();
        city_lbl = new javax.swing.JLabel();
        state_txt = new javax.swing.JTextField();
        state_lbl = new javax.swing.JLabel();
        zip_txt = new javax.swing.JTextField();
        zip_lbl = new javax.swing.JLabel();
        signup_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(169, 203, 186));

        lbl_admintitle.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        lbl_admintitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_admintitle.setText("Create Manager Profile");

        name_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_lbl.setText("Name:");

        uname_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uname_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uname_lbl.setText("Username:");

        pwd_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pwd_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pwd_lbl.setText("Password:");

        ngo_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ngo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ngo_lbl.setText("NGO Name:");

        ngolist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        depart_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        depart_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depart_lbl.setText("Department:");

        address_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        address_lbl.setText("Address:");

        city_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        city_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        city_lbl.setText("City:");

        state_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        state_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        state_lbl.setText("State:");

        zip_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zip_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zip_lbl.setText("Zip Code:");

        signup_btn.setBackground(new java.awt.Color(255, 204, 51));
        signup_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signup_btn.setText("Sign Up");
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });

        back_btn.setBackground(new java.awt.Color(255, 204, 51));
        back_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209)
                        .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(331, 331, 331))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_admintitle, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(name_lbl)
                                        .addComponent(uname_lbl))
                                    .addComponent(pwd_lbl)
                                    .addComponent(ngo_lbl)
                                    .addComponent(depart_lbl))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ngolist, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(depart_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(city_lbl)
                                    .addComponent(address_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(state_lbl)
                                    .addComponent(zip_lbl))))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(state_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zip_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {add_txt, city_txt, depart_txt, name_txt, ngolist, pass_txt, state_txt, uname_txt, zip_txt});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {address_lbl, city_lbl, depart_lbl, name_lbl, ngo_lbl, pwd_lbl, state_lbl, uname_lbl, zip_lbl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lbl_admintitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(city_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city_lbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(state_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state_lbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zip_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zip_lbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_lbl)
                            .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uname_lbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwd_lbl))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ngolist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngo_lbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depart_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depart_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {add_txt, address_lbl, city_lbl, city_txt, depart_lbl, depart_txt, name_lbl, name_txt, ngo_lbl, ngolist, pass_txt, pwd_lbl, state_lbl, state_txt, uname_lbl, uname_txt, zip_lbl, zip_txt});

    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed

        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        // TODO add your handling code here:
        
        try {
            if(EmpytyFieldValidation())
            {
                if(RegexValidation())
                {
                    String address = add_txt.getText() + "," + city_txt.getText() + "," + state_txt.getText() + "," + zip_txt.getText();


                    Manager doctor = new Manager(uname_txt.getText(), pass_txt.getText(), uname_txt.getText(), name_txt.getText(), address, "male", String.valueOf(docnumber), new Date(),depart_txt.getText(),ngolist.getSelectedItem().toString());

                    operatingSystem.addManager(doctor);
                    dB4OUtility.storeSystem(operatingSystem);

                    MainJFrameForm suc = new MainJFrameForm();
                    ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
                    suc.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Some Error in entered data.Please check over the red fields to know more.");
                    validationCheck=true;
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Data Cant be empty. Please check over the red fields to know more.");
                ValidationStatus=true;
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Recepient not registered, Try again");
            ValidationStatus=true;
        }
        

    }//GEN-LAST:event_signup_btnActionPerformed


    private boolean RegexValidation() {
    if(!name_txt.getText().matches("^[a-zA-Z ]+$"))
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        // if(!txtContact.getText().matches("^[0-9]{10}$"))
        // {
        //     txtContact.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        //     txtContact.setToolTipText("Please enter a 10 digit number");
        //     validationCheck=false;
        // }


        if(!zip_txt.getText().matches("^[0-9]{5}$"))
        {
            zip_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            zip_txt.setToolTipText("Please enter a 5 digit number");
            validationCheck=false;
        }

        // if(!txt_spc.getText().matches("^[0-9]{5}$"))
        // {
        //     txt_spc.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        //     txt_spc.setToolTipText("Please enter a 5 digit number");
        //     validationCheck=false;
        // }

        return validationCheck;


    }   


    private boolean EmpytyFieldValidation() {
        if(add_txt.getText().equals(null) || add_txt.getText().trim().isEmpty() )
        {
            add_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            add_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!add_txt.getText().equals(null) && !add_txt.getText().trim().isEmpty() )
        {
            add_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(city_txt.getText().equals(null) || city_txt.getText().trim().isEmpty() )
        {
            city_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            city_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!city_txt.getText().equals(null) && !city_txt.getText().trim().isEmpty() )
        {
            city_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(name_txt.getText().equals(null) || name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!name_txt.getText().equals(null) && !name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(pass_txt.getText().equals(null) || pass_txt.getText().trim().isEmpty() )
        {
            pass_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            pass_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!pass_txt.getText().equals(null) && !pass_txt.getText().trim().isEmpty() )
        {
            pass_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(state_txt.getText().equals(null) || state_txt.getText().trim().isEmpty() )
        {
            state_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            state_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!state_txt.getText().equals(null) && !state_txt.getText().trim().isEmpty() )
        {
            state_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(uname_txt.getText().equals(null) || uname_txt.getText().trim().isEmpty() )
            {
                uname_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                uname_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatus= false;
            }
        if(!uname_txt.getText().equals(null) && !uname_txt.getText().trim().isEmpty() )
        {
            uname_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(zip_txt.getText().equals(null) || zip_txt.getText().trim().isEmpty() )
            {
                zip_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                zip_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatus= false;
            }
        if(!zip_txt.getText().equals(null) && !zip_txt.getText().trim().isEmpty() )
        {
            zip_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(depart_txt.getText().equals(null) || depart_txt.getText().trim().isEmpty() )
            {
                depart_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                depart_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatus= false;
            }
        if(!depart_txt.getText().equals(null) && !depart_txt.getText().trim().isEmpty() )
        {
            depart_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        // if(txtContact.getText().equals(null) || txtContact.getText().trim().isEmpty() )
        //     {
        //         txtContact.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        //         txtContact.setToolTipText("This Field Cannot be empty");
        //         ValidationStatus= false;
        //     }
        // if(!txtContact.getText().equals(null) && !txtContact.getText().trim().isEmpty() )
        // {
        //     txtContact.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        // }
        
        return ValidationStatus;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_txt;
    private javax.swing.JLabel address_lbl;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel city_lbl;
    private javax.swing.JTextField city_txt;
    private javax.swing.JLabel depart_lbl;
    private javax.swing.JTextField depart_txt;
    private javax.swing.JLabel lbl_admintitle;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField name_txt;
    private javax.swing.JLabel ngo_lbl;
    private javax.swing.JComboBox<String> ngolist;
    private javax.swing.JPasswordField pass_txt;
    private javax.swing.JLabel pwd_lbl;
    private javax.swing.JButton signup_btn;
    private javax.swing.JLabel state_lbl;
    private javax.swing.JTextField state_txt;
    private javax.swing.JLabel uname_lbl;
    private javax.swing.JTextField uname_txt;
    private javax.swing.JLabel zip_lbl;
    private javax.swing.JTextField zip_txt;
    // End of variables declaration//GEN-END:variables
}
