/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.DonationCentreInterface;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.DonationCentre.UserDonor;
import finalprojectBackend.Enterprise.DonationCentre.BankDonor;
import finalprojectUserInterface.MainJFrameForm;
import finalprojectUserInterface.DonationCentreInterface.DonarLoginPages.DonationCentreAdminLogin;
import finalprojectUserInterface.DonationCentreInterface.DonarLoginPages.DonarLogin;
import javax.swing.JOptionPane;
/**
 *
 * @author sourabh
 */
public class DonarBankLandingPage extends javax.swing.JPanel {

    /**
     * Creates new form DonarBankLandingPage
     */
    MainJFrameForm MainLPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    
    public DonarBankLandingPage(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DonarjLabel1 = new javax.swing.JLabel();
        RoleLabel = new javax.swing.JLabel();
        RoleCmb = new javax.swing.JComboBox<>();
        UsernameLabel = new javax.swing.JLabel();
        UsernameTxt = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        PassTxt = new javax.swing.JPasswordField();
        Login_btn = new javax.swing.JButton();
        Signinbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(172, 162, 195));

        DonarjLabel1.setBackground(new java.awt.Color(0, 0, 0));
        DonarjLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        DonarjLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DonarjLabel1.setText("DONATION CENTER");

        RoleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RoleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoleLabel.setText("Role:");

        RoleCmb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RoleCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donor","Donor Admin"}));
        RoleCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleCmbActionPerformed(evt);
            }
        });

        UsernameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernameLabel.setText("Username:");

        passwordLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLbl.setText("Password:");

        Login_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Login_btn.setText("Login");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });

        Signinbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Signinbtn.setText("Sign Up");
        Signinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLbl)
                            .addComponent(UsernameLabel)
                            .addComponent(RoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Signinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RoleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(DonarjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 230, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {RoleLabel, UsernameLabel, passwordLbl});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {PassTxt, RoleCmb, UsernameTxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(DonarjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLbl))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Signinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(274, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {PassTxt, RoleCmb, RoleLabel, UsernameLabel, UsernameTxt, passwordLbl});

    }// </editor-fold>//GEN-END:initComponents

    private void RoleCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleCmbActionPerformed
        // TODO add your handling code here:
        System.out.println(RoleCmb.getSelectedItem().toString());
        if (RoleCmb.getSelectedItem().toString() == "Admin") {
            Signinbtn.setEnabled(false);
        } else {
            Signinbtn.setEnabled(true);
        }
    }//GEN-LAST:event_RoleCmbActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        // TODO add your handling code here:
        
        try {
            if (RoleCmb.getSelectedItem().toString() == "Donor Admin") {
            BankDonor donbank = (BankDonor) operatingSystem.loginAuthentication(UsernameTxt.getText(), PassTxt.getText());
            if(donbank == null){
                JOptionPane.showMessageDialog(this, "Incorrect credential");
            }else{
                DonationCentreAdminLogin ap = new DonationCentreAdminLogin(MainLPage, dB4OUtility, operatingSystem, donbank);
                MainLPage.setContentPane(ap);
                MainLPage.invalidate();
                MainLPage.validate();
                return;
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Donor Bank does not exist. Try again");
        }
        

        try {
            if (RoleCmb.getSelectedItem().toString() == "Donor") {
            UserDonor don = (UserDonor) operatingSystem.loginAuthentication(UsernameTxt.getText(), PassTxt.getText());
            if(don == null){
                JOptionPane.showMessageDialog(this, "Incorrect credential");
            }else{
                DonarLogin ap = new DonarLogin(MainLPage, dB4OUtility, operatingSystem, don);
                MainLPage.setContentPane(ap);
                MainLPage.invalidate();
                MainLPage.validate();
                return;
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Donor does not exist. Try again");
        }
    }//GEN-LAST:event_Login_btnActionPerformed

    private void SigninbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninbtnActionPerformed
        // TODO add your handling code here:

        if (RoleCmb.getSelectedItem().toString() == "Donor") {
            DonationCentreSignUp signdon = new DonationCentreSignUp(MainLPage, dB4OUtility, operatingSystem);
            MainLPage.setContentPane(signdon);
            MainLPage.invalidate();
            MainLPage.validate();
        }

        if (RoleCmb.getSelectedItem().toString() == "Donor Admin") {
            DonationCentreAdminSignUp s = new DonationCentreAdminSignUp(MainLPage, dB4OUtility, operatingSystem);
            MainLPage.setContentPane(s);
            MainLPage.invalidate();
            MainLPage.validate();
        }
    }//GEN-LAST:event_SigninbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DonarjLabel1;
    private javax.swing.JButton Login_btn;
    private javax.swing.JPasswordField PassTxt;
    private javax.swing.JComboBox<String> RoleCmb;
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JButton Signinbtn;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTxt;
    private javax.swing.JLabel passwordLbl;
    // End of variables declaration//GEN-END:variables
}
