/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.DonationCentreInterface;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.DonationCentre.UserDonor;
import finalprojectBackend.Enterprise.DonationCentre.BankDonor;
import finalprojectUserInterface.MainJFrameForm;
import java.awt.Color;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author sourabh
 */
public class DonationCentreSignUp extends javax.swing.JPanel {

    /**
     * Creates new form DonationCentreSignUp
     */
    boolean ValidationStatus = true;
    boolean validationCheck = true;
    
    MainJFrameForm MainLoginPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    
    public DonationCentreSignUp(MainJFrameForm MainLPage, DB4OUtility dB4OUtility, OperatingSystem operatingSystem) {
        initComponents();
        this.MainLoginPage = MainLPage;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        
        for(BankDonor db: operatingSystem.getBankDonorDirectory()){
            bank_txt.addItem(db.getNameEnterprise());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donarprofile_lbl = new javax.swing.JLabel();
        Name_lbl = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        uname_lbl = new javax.swing.JLabel();
        uname_txt = new javax.swing.JTextField();
        pswd_lbl = new javax.swing.JLabel();
        pwd_txt = new javax.swing.JPasswordField();
        addrlbl = new javax.swing.JLabel();
        add_txt = new javax.swing.JTextField();
        Citylbl = new javax.swing.JLabel();
        city_txt = new javax.swing.JTextField();
        Statelbl = new javax.swing.JLabel();
        state_txt = new javax.swing.JTextField();
        Ziplbl = new javax.swing.JLabel();
        zip_txt = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        sign_btn = new javax.swing.JButton();
        genderlbl = new javax.swing.JLabel();
        cmb_gender = new javax.swing.JComboBox<>();
        telenumlbl = new javax.swing.JLabel();
        num_txt = new javax.swing.JTextField();
        doblbl = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        donorbnknamelbl = new javax.swing.JLabel();
        bank_txt = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(169, 146, 125));

        donarprofile_lbl.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        donarprofile_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        donarprofile_lbl.setText("Create Donor ");

        Name_lbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Name_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name_lbl.setText("Name:");

        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name_txtKeyReleased(evt);
            }
        });

        uname_lbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        uname_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uname_lbl.setText("Username:");

        uname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname_txtActionPerformed(evt);
            }
        });

        pswd_lbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pswd_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pswd_lbl.setText("Password:");

        pwd_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd_txtActionPerformed(evt);
            }
        });

        addrlbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addrlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addrlbl.setText("Address:");

        add_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_txtActionPerformed(evt);
            }
        });
        add_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                add_txtKeyReleased(evt);
            }
        });

        Citylbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Citylbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Citylbl.setText("City:");

        city_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_txtActionPerformed(evt);
            }
        });
        city_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                city_txtKeyReleased(evt);
            }
        });

        Statelbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Statelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Statelbl.setText("State:");

        state_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                state_txtActionPerformed(evt);
            }
        });
        state_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                state_txtKeyReleased(evt);
            }
        });

        Ziplbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Ziplbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ziplbl.setText("Zip Code:");

        zip_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zip_txtActionPerformed(evt);
            }
        });
        zip_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zip_txtKeyReleased(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(255, 204, 51));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        sign_btn.setBackground(new java.awt.Color(255, 204, 51));
        sign_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sign_btn.setText("Sign Up");
        sign_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_btnActionPerformed(evt);
            }
        });

        genderlbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        genderlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genderlbl.setText("Gender:");

        cmb_gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        telenumlbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        telenumlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telenumlbl.setText("Phone no.:");

        num_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_txtActionPerformed(evt);
            }
        });
        num_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num_txtKeyReleased(evt);
            }
        });

        doblbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        doblbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doblbl.setText("Date of Birth:");

        txt_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dobActionPerformed(evt);
            }
        });
        txt_dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_dobKeyReleased(evt);
            }
        });

        donorbnknamelbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        donorbnknamelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        donorbnknamelbl.setText("Donation Center:");

        bank_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bank_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bank_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(donorbnknamelbl)
                            .addComponent(telenumlbl)
                            .addComponent(genderlbl)
                            .addComponent(pswd_lbl)
                            .addComponent(uname_lbl)
                            .addComponent(Name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bank_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addrlbl)
                            .addComponent(Citylbl)
                            .addComponent(Statelbl)
                            .addComponent(Ziplbl)
                            .addComponent(doblbl))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zip_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(donarprofile_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(448, 448, 448))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sign_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(496, 496, 496))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Citylbl, Name_lbl, Statelbl, Ziplbl, addrlbl, doblbl, donorbnknamelbl, genderlbl, pswd_lbl, telenumlbl, uname_lbl});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {add_txt, bank_txt, city_txt, cmb_gender, name_txt, num_txt, pwd_txt, state_txt, txt_dob, uname_txt, zip_txt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(donarprofile_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uname_lbl)
                            .addComponent(uname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pswd_lbl)
                            .addComponent(pwd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderlbl)
                            .addComponent(cmb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telenumlbl)
                            .addComponent(num_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(donorbnknamelbl)
                            .addComponent(bank_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addrlbl)
                            .addComponent(add_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Citylbl)
                            .addComponent(city_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Statelbl)
                            .addComponent(state_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ziplbl)
                            .addComponent(zip_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doblbl)
                            .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addComponent(sign_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Citylbl, Name_lbl, Statelbl, Ziplbl, add_txt, addrlbl, bank_txt, city_txt, cmb_gender, doblbl, donorbnknamelbl, genderlbl, name_txt, num_txt, pswd_lbl, pwd_txt, state_txt, telenumlbl, txt_dob, uname_lbl, uname_txt, zip_txt});

    }// </editor-fold>//GEN-END:initComponents

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
    }//GEN-LAST:event_name_txtActionPerformed

    private void name_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_txtKeyReleased
    }//GEN-LAST:event_name_txtKeyReleased

    private void uname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname_txtActionPerformed
    }//GEN-LAST:event_uname_txtActionPerformed

    private void pwd_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd_txtActionPerformed
    }//GEN-LAST:event_pwd_txtActionPerformed

    private void add_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_txtActionPerformed
    }//GEN-LAST:event_add_txtActionPerformed

    private void add_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_add_txtKeyReleased
    }//GEN-LAST:event_add_txtKeyReleased

    private void city_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_txtActionPerformed
    }//GEN-LAST:event_city_txtActionPerformed

    private void city_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_city_txtKeyReleased
    }//GEN-LAST:event_city_txtKeyReleased

    private void state_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_state_txtActionPerformed
    }//GEN-LAST:event_state_txtActionPerformed

    private void state_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_state_txtKeyReleased
    }//GEN-LAST:event_state_txtKeyReleased

    private void zip_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zip_txtActionPerformed
    }//GEN-LAST:event_zip_txtActionPerformed

    private void zip_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zip_txtKeyReleased
    }//GEN-LAST:event_zip_txtKeyReleased

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        MainJFrameForm suc = new MainJFrameForm();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void sign_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_btnActionPerformed
        // TODO add your handling code here:
        try {
            if(EmpytyFieldValidation())
            {
                if(RegexValidation())
                {
                    String address = add_txt.getText() + "," + city_txt.getText() + "," + state_txt.getText() + "," + zip_txt.getText();

                    UserDonor donor = new UserDonor(uname_txt.getText(), pwd_txt.getText(), "idid", name_txt.getText(), address, cmb_gender.getSelectedItem().toString(), num_txt.getText(), new Date(),bank_txt.getSelectedItem().toString());

                    operatingSystem.donorAdd(donor);
                    dB4OUtility.storeSystem(operatingSystem);

                    MainJFrameForm suc = new MainJFrameForm();
                    ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
                    suc.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Some Error in entered data.Please check over the red fields to know more.");
                    validationCheck=true;
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Data Cant be empty. Please check over the red fields to know more.");
                ValidationStatus=true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Donor not registered, Try again");
            ValidationStatus=true;
        }
        
    }//GEN-LAST:event_sign_btnActionPerformed

    private void num_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_txtActionPerformed
    }//GEN-LAST:event_num_txtActionPerformed

    private void num_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num_txtKeyReleased
    }//GEN-LAST:event_num_txtKeyReleased

    private void txt_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dobActionPerformed
    }//GEN-LAST:event_txt_dobActionPerformed

    private void txt_dobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dobKeyReleased
    }//GEN-LAST:event_txt_dobKeyReleased

    private void bank_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bank_txtActionPerformed
    }//GEN-LAST:event_bank_txtActionPerformed

    private boolean RegexValidation() {
    if(!name_txt.getText().matches("^[a-zA-Z ]+$"))
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("Please enter only characters and space.");
            validationCheck=false;
        }
        
        if(!num_txt.getText().matches("^[0-9]{10}$"))
        {
            num_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            num_txt.setToolTipText("Please enter a 10 digit number");
            validationCheck=false;
        }


        if(!zip_txt.getText().matches("^[0-9]{5}$"))
        {
            zip_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            zip_txt.setToolTipText("Please enter a 5 digit number");
            validationCheck=false;
        }

        // if(!gendercmb.getText().matches("^[0-9]{5}$"))
        // {
        //     gendercmb.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        //     gendercmb.setToolTipText("Please enter a 5 digit number");
        //     validationCheck=false;
        // }

        return validationCheck;


    }   


    private boolean EmpytyFieldValidation() {
        if(add_txt.getText().equals(null) || add_txt.getText().trim().isEmpty() )
        {
            add_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            add_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!add_txt.getText().equals(null) && !add_txt.getText().trim().isEmpty() )
        {
            add_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(city_txt.getText().equals(null) || city_txt.getText().trim().isEmpty() )
        {
            city_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            city_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!city_txt.getText().equals(null) && !city_txt.getText().trim().isEmpty() )
        {
            city_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(name_txt.getText().equals(null) || name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            name_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!name_txt.getText().equals(null) && !name_txt.getText().trim().isEmpty() )
        {
            name_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(pwd_txt.getText().equals(null) || pwd_txt.getText().trim().isEmpty() )
        {
            pwd_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            pwd_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!pwd_txt.getText().equals(null) && !pwd_txt.getText().trim().isEmpty() )
        {
            pwd_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(state_txt.getText().equals(null) || state_txt.getText().trim().isEmpty() )
        {
            state_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            state_txt.setToolTipText("This Field Cannot be empty");
            ValidationStatus= false;
        }
        if(!state_txt.getText().equals(null) && !state_txt.getText().trim().isEmpty() )
        {
            state_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(uname_txt.getText().equals(null) || uname_txt.getText().trim().isEmpty() )
            {
                uname_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                uname_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatus= false;
            }
        if(!uname_txt.getText().equals(null) && !uname_txt.getText().trim().isEmpty() )
        {
            uname_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(zip_txt.getText().equals(null) || zip_txt.getText().trim().isEmpty() )
            {
                zip_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                zip_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatus= false;
            }
        if(!zip_txt.getText().equals(null) && !zip_txt.getText().trim().isEmpty() )
        {
            zip_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

 

        if(num_txt.getText().equals(null) || num_txt.getText().trim().isEmpty() )
            {
                num_txt.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                num_txt.setToolTipText("This Field Cannot be empty");
                ValidationStatus= false;
            }
        if(!num_txt.getText().equals(null) && !num_txt.getText().trim().isEmpty() )
        {
            num_txt.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }

        if(txt_dob.getText().equals(null) || txt_dob.getText().trim().isEmpty() )
            {
                txt_dob.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                txt_dob.setToolTipText("This Field Cannot be empty");
                ValidationStatus= false;
            }
        if(!txt_dob.getText().equals(null) && !txt_dob.getText().trim().isEmpty() )
        {
            txt_dob.setBorder(BorderFactory.createLineBorder(Color.BLUE, 1));
        }
        
        return ValidationStatus;
    }

    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Citylbl;
    private javax.swing.JLabel Name_lbl;
    private javax.swing.JLabel Statelbl;
    private javax.swing.JLabel Ziplbl;
    private javax.swing.JTextField add_txt;
    private javax.swing.JLabel addrlbl;
    private javax.swing.JComboBox<String> bank_txt;
    private javax.swing.JButton btn_back;
    private javax.swing.JTextField city_txt;
    private javax.swing.JComboBox<String> cmb_gender;
    private javax.swing.JLabel doblbl;
    private javax.swing.JLabel donarprofile_lbl;
    private javax.swing.JLabel donorbnknamelbl;
    private javax.swing.JLabel genderlbl;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField num_txt;
    private javax.swing.JLabel pswd_lbl;
    private javax.swing.JPasswordField pwd_txt;
    private javax.swing.JButton sign_btn;
    private javax.swing.JTextField state_txt;
    private javax.swing.JLabel telenumlbl;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JLabel uname_lbl;
    private javax.swing.JTextField uname_txt;
    private javax.swing.JTextField zip_txt;
    // End of variables declaration//GEN-END:variables
}
