/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.BusinessOwner;

import TheBusiness.Personnel.Person;
import UserInterface.User.AccountSecurityJFrame;
import UserInterface.User.ViewUserDetailsJFrame;
import java.awt.Color;
import java.awt.Point;



/**
 *
 * @author mac
 */
public class BusinessOwnerDashboardJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BusinessOwnerDashboardJFrame
     */
    Person person;
    public BusinessOwnerDashboardJFrame(Person person) {
        this.person = person;
        initComponents();
        Color lightBlue = new Color(173, 216, 230);
        getContentPane().setBackground(lightBlue);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Set close operation
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCustomer = new javax.swing.JButton();
        btnManageSuppliers = new javax.swing.JButton();
        btnManageMarketing = new javax.swing.JButton();
        btnManageSales = new javax.swing.JButton();
        btnUserDetails = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAccountSecurity = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnManageCustomer.setText("Manage Customer");
        btnManageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomerActionPerformed(evt);
            }
        });

        btnManageSuppliers.setText("Manage Suppliers");
        btnManageSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSuppliersActionPerformed(evt);
            }
        });

        btnManageMarketing.setText("Manage Marketing ");
        btnManageMarketing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketingActionPerformed(evt);
            }
        });

        btnManageSales.setText("Manage Sales");
        btnManageSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSalesActionPerformed(evt);
            }
        });

        btnUserDetails.setText("User Profile");
        btnUserDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDetailsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Portal");

        btnAccountSecurity.setText("Account Security");
        btnAccountSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountSecurityActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265))))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManageCustomer)
                    .addComponent(btnManageSuppliers)
                    .addComponent(btnUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageSales, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageMarketing)
                    .addComponent(btnAccountSecurity))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAccountSecurity, btnManageCustomer, btnManageMarketing, btnManageSales, btnManageSuppliers, btnUserDetails});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccountSecurity))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageSales)
                    .addComponent(btnManageCustomer))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageSuppliers)
                    .addComponent(btnManageMarketing))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAccountSecurity, btnManageCustomer, btnManageMarketing, btnManageSales, btnManageSuppliers, btnUserDetails});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomerActionPerformed
        // TODO add your handling code here:  
        Point parentFramePosition = this.getLocation();
        this.setVisible(false);
        ManageCustomerBusinessOwnerJFrame manageCustomer = new ManageCustomerBusinessOwnerJFrame(this);
        manageCustomer.setLocation(parentFramePosition);
        manageCustomer.setVisible(true); 
    }//GEN-LAST:event_btnManageCustomerActionPerformed

    private void btnManageSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSuppliersActionPerformed
        // TODO add your handling code here:
        Point parentFramePosition = this.getLocation();
        this.setVisible(false);
        ManageSuppliersJFrame manageSupplier = new ManageSuppliersJFrame(this);
        manageSupplier.setLocation(parentFramePosition);
        manageSupplier.setVisible(true);
    }//GEN-LAST:event_btnManageSuppliersActionPerformed

    private void btnManageMarketingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketingActionPerformed
        // TODO add your handling code here:
        Point parentFramePosition = this.getLocation();
        this.setVisible(false);
        ManageMarketingBusinessOwnerJFrame manageMarketing = new ManageMarketingBusinessOwnerJFrame(this);
        manageMarketing.setLocation(parentFramePosition);
        manageMarketing.setVisible(true);
        
    }//GEN-LAST:event_btnManageMarketingActionPerformed

    private void btnManageSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSalesActionPerformed
        // TODO add your handling code here:
        Point parentFramePosition = this.getLocation();
        this.setVisible(false);
        ManageSalesBusinessOwnerJFrame manageSales = new ManageSalesBusinessOwnerJFrame(this);
        manageSales.setLocation(parentFramePosition);
        manageSales.setVisible(true);
    }//GEN-LAST:event_btnManageSalesActionPerformed

    private void btnUserDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDetailsActionPerformed
        // TODO add your handling code here:
        Point parentFramePosition = this.getLocation();
        this.setVisible(false);
//        this.dispose();
        ViewUserDetailsJFrame userInfo = new ViewUserDetailsJFrame(this, this.person);
        userInfo.setLocation(parentFramePosition);
        userInfo.setVisible(true);
    }//GEN-LAST:event_btnUserDetailsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnAccountSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountSecurityActionPerformed
        // TODO add your handling code here:
        Point parentFramePosition = this.getLocation();
        this.setVisible(false);
        AccountSecurityJFrame accSecurity = new AccountSecurityJFrame(this, this.person);
        accSecurity.setLocation(parentFramePosition);
        accSecurity.setVisible(true);
    }//GEN-LAST:event_btnAccountSecurityActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountSecurity;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageCustomer;
    private javax.swing.JButton btnManageMarketing;
    private javax.swing.JButton btnManageSales;
    private javax.swing.JButton btnManageSuppliers;
    private javax.swing.JButton btnUserDetails;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
