/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Customer;

import DataManagement.DataManager;
import TheBusiness.Personnel.Customer;
import TheBusiness.Personnel.Person;
import UserInterface.User.AccountSecurityJFrame;
import UserInterface.User.ViewUserDetailsJFrame;
import java.awt.Color;
import java.awt.Point;

/**
 *
 * @author sourabhkumar
 */
public class CustomerPortalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerPortalJFrame
     */
    Customer customer;
    Person person;
    public CustomerPortalJFrame(Customer customer) {
        this.customer = customer;
        this.person = DataManager.personDirectory.get(customer.getPersonId());
        initComponents();
        Color lightBlue = new Color(173, 216, 230);
        getContentPane().setBackground(lightBlue);
        jCustomerSplitPane.getBottomComponent().setBackground(lightBlue);
        jCustomerSplitPane.getTopComponent().setBackground(lightBlue);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Set close operation

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jCustomerSplitPane = new javax.swing.JSplitPane();
        jCustomerControlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnOrderHistory = new javax.swing.JButton();
        btnManageOrder = new javax.swing.JButton();
        btnPwd = new javax.swing.JButton();
        btnViewUser = new javax.swing.JButton();
        btnPwd1 = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jCustomerWorkPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCustomerSplitPane.setDividerLocation(200);
        jCustomerSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jCustomerControlPanel.setPreferredSize(new java.awt.Dimension(700, 200));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Portal");

        btnOrderHistory.setText("Order History");
        btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistoryActionPerformed(evt);
            }
        });

        btnManageOrder.setText("Manage Order");
        btnManageOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrderActionPerformed(evt);
            }
        });

        btnPwd.setText("Account Security");
        btnPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPwdActionPerformed(evt);
            }
        });

        btnViewUser.setText("User Profile");
        btnViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUserActionPerformed(evt);
            }
        });

        btnPwd1.setText("Lets Shop");
        btnPwd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPwd1ActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCustomerControlPanelLayout = new javax.swing.GroupLayout(jCustomerControlPanel);
        jCustomerControlPanel.setLayout(jCustomerControlPanelLayout);
        jCustomerControlPanelLayout.setHorizontalGroup(
            jCustomerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCustomerControlPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jCustomerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jCustomerControlPanelLayout.createSequentialGroup()
                        .addGroup(jCustomerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPwd))
                        .addGap(96, 96, 96)
                        .addComponent(btnPwd1)
                        .addGap(86, 86, 86)
                        .addGroup(jCustomerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageOrder, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOrderHistory, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jCustomerControlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(btnLogOut)))
                .addGap(51, 51, 51))
        );

        jCustomerControlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageOrder, btnOrderHistory, btnPwd, btnPwd1, btnViewUser});

        jCustomerControlPanelLayout.setVerticalGroup(
            jCustomerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCustomerControlPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jCustomerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCustomerControlPanelLayout.createSequentialGroup()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jCustomerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManageOrder)
                            .addComponent(btnViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jCustomerControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPwd)
                            .addComponent(btnOrderHistory)))
                    .addGroup(jCustomerControlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnPwd1)))
                .addGap(27, 27, 27))
        );

        jCustomerControlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnManageOrder, btnOrderHistory, btnPwd, btnPwd1, btnViewUser});

        jCustomerSplitPane.setTopComponent(jCustomerControlPanel);

        javax.swing.GroupLayout jCustomerWorkPanelLayout = new javax.swing.GroupLayout(jCustomerWorkPanel);
        jCustomerWorkPanel.setLayout(jCustomerWorkPanelLayout);
        jCustomerWorkPanelLayout.setHorizontalGroup(
            jCustomerWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jCustomerWorkPanelLayout.setVerticalGroup(
            jCustomerWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jCustomerSplitPane.setRightComponent(jCustomerWorkPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCustomerSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCustomerSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPwdActionPerformed
        // TODO add your handling code here:
        Point parentFramePosition = this.getLocation();
        this.setVisible(false);
        AccountSecurityJFrame accSecurity = new AccountSecurityJFrame(this, this.person);
        accSecurity.setLocation(parentFramePosition);
        accSecurity.setVisible(true);
    }//GEN-LAST:event_btnPwdActionPerformed

    private void btnPwd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPwd1ActionPerformed
        // TODO add your handling code here:
        if (this.customer.getChannelId() == -1) {
            ChooseChannelJPanel choose = new ChooseChannelJPanel(this, this.customer);
            jCustomerSplitPane.setBottomComponent(choose);
        } else {
            LetsShopJPanel shopPanel = new LetsShopJPanel(this, this.customer);
            jCustomerSplitPane.setBottomComponent(shopPanel);
        }
       
    }//GEN-LAST:event_btnPwd1ActionPerformed

    private void btnViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUserActionPerformed
        // TODO add your handling code here:
        Point parentFramePosition = this.getLocation();
        this.setVisible(false);
//        this.dispose();
        ViewUserDetailsJFrame userInfo = new ViewUserDetailsJFrame(this, this.person);
        userInfo.setLocation(parentFramePosition);
        userInfo.setVisible(true);
        
    }//GEN-LAST:event_btnViewUserActionPerformed

    private void btnManageOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrderActionPerformed
        // TODO add your handling code here:
        ManageOrderJPanel orderPanel = new ManageOrderJPanel(this, this.customer);
        jCustomerSplitPane.setBottomComponent(orderPanel);
    }//GEN-LAST:event_btnManageOrderActionPerformed

    private void btnOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryActionPerformed
        // TODO add your handling code here:
        OrderHistoryJPanel orderHistory = new OrderHistoryJPanel(this, this.customer);
        jCustomerSplitPane.setBottomComponent(orderHistory);
    }//GEN-LAST:event_btnOrderHistoryActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageOrder;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JButton btnPwd;
    private javax.swing.JButton btnPwd1;
    private javax.swing.JButton btnViewUser;
    private javax.swing.JPanel jCustomerControlPanel;
    private javax.swing.JSplitPane jCustomerSplitPane;
    private javax.swing.JPanel jCustomerWorkPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
