/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package finalprojectUserInterface.NGOInterface.LoginPage.NGOAdminLoginPages;

import finalprojectBackend.DB4OUtility.DB4OUtility;
import finalprojectBackend.OperatingSystem.OperatingSystem;
import finalprojectBackend.Enterprise.NGO.NGOClass;
import finalprojectBackend.Enterprise.NGO.Caretaker;
import finalprojectUserInterface.MainJFrameForm;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sourabh
 */
public class AdminPageForCaretakers extends javax.swing.JPanel {

    /**
     * Creates new form AdminPageForCaretakers
     */
    MainJFrameForm MainLoginPage;
    private OperatingSystem operatingSystem;
    private DB4OUtility dB4OUtility;
    NGOClass ngo;

    public AdminPageForCaretakers(MainJFrameForm mainScreen, DB4OUtility dB4OUtility, OperatingSystem operatingSystem, NGOClass h) {
        initComponents();
        this.MainLoginPage = mainScreen;
        this.dB4OUtility = dB4OUtility;
        this.operatingSystem = operatingSystem;
        this.ngo = h;
        populateCaretakerTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_1 = new javax.swing.JTable();
        CaretakerTitle = new javax.swing.JLabel();
        delete_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(169, 146, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "UserName", "Gender", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 1020, 480));

        CaretakerTitle.setBackground(new java.awt.Color(255, 255, 255));
        CaretakerTitle.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        CaretakerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CaretakerTitle.setText("Manage Caretaker");
        jPanel1.add(CaretakerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 280, 70));

        delete_btn.setBackground(new java.awt.Color(255, 204, 51));
        delete_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 690, 140, 40));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) table_1.getModel();
        String nurseUName = model.getValueAt(selectedRow, 1).toString();
        System.out.println(" Nurse username: " + nurseUName);
        operatingSystem.deleteCaretakerUser(nurseUName);
        dB4OUtility.storeSystem(operatingSystem);
        populateCaretakerTable();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void populateCaretakerTable(){
    DefaultTableModel model = (DefaultTableModel) table_1.getModel();
    model.setRowCount(0);

    for (Caretaker n : operatingSystem.getCaretakerDirectory()) {

        if (n.getNGOName().equals(ngo.getNameEnterprise())) {
            Object[] row = new Object[5];
            row[0] = n.getNamePerson();
            row[1] = n.getpName();
            row[2] = n.getPgender();
            row[3] = n.getAddr();
            model.addRow(row);

        }

    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CaretakerTitle;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_1;
    // End of variables declaration//GEN-END:variables
}
