/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.MarketManager;

import DataManagement.DataManager;
import TheBusiness.MarketModel.Channel;
import TheBusiness.MarketModel.Market;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sourabhkumar
 */
public class ViewMarketJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewMarketJFrame
     */
    javax.swing.JFrame parentFrame;
    Market market;
    public ViewMarketJFrame(JFrame parentFrame, Market market) {
        this.parentFrame = parentFrame;
        this.market = market;
        initComponents();
        loadData();
        Color lightBlue = new Color(173, 216, 230);
        getContentPane().setBackground(lightBlue);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Set close operation
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                loadParentFrame();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAddChannelToMarket = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRemoveChannelFromMarket = new javax.swing.JButton();
        txtMarketID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMarketDecription = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAddedChannelToMarket = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNotAddedChannelToMarket = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtMarketName = new javax.swing.JTextField();
        btnManageMarketBundles = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Market");

        btnBack.setText("<- Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddChannelToMarket.setText("Add");
        btnAddChannelToMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChannelToMarketActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Description");

        btnRemoveChannelFromMarket.setText("Remove");
        btnRemoveChannelFromMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveChannelFromMarketActionPerformed(evt);
            }
        });

        txtMarketID.setEditable(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Remove Channel From Market");

        txtMarketDecription.setColumns(20);
        txtMarketDecription.setRows(5);
        jScrollPane1.setViewportView(txtMarketDecription);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add Channel to Market");

        tblAddedChannelToMarket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Channel ID", "Channel Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAddedChannelToMarket);

        tblNotAddedChannelToMarket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Channel ID", "Channel Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblNotAddedChannelToMarket);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ID");

        txtMarketName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarketNameActionPerformed(evt);
            }
        });

        btnManageMarketBundles.setText("Manage Market Bundles ");
        btnManageMarketBundles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketBundlesActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnBack)
                .addGap(171, 171, 171)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(btnAddChannelToMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarketID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSave)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addComponent(btnRemoveChannelFromMarket)))
                    .addComponent(btnManageMarketBundles, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, txtMarketID, txtMarketName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(btnManageMarketBundles, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarketID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarketName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddChannelToMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveChannelFromMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel4, jLabel7, txtMarketID, txtMarketName});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarketNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarketNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarketNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        loadParentFrame();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnManageMarketBundlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketBundlesActionPerformed
        // TODO add your handling code here:
        Point parentFramePosition = this.getLocation();
        this.setVisible(false);
//        this.dispose();
        ManageMarketBundleJFrame mngBundle = new ManageMarketBundleJFrame(this, market);
        mngBundle.setLocation(parentFramePosition);
        mngBundle.setVisible(true);
    }//GEN-LAST:event_btnManageMarketBundlesActionPerformed

    private void btnAddChannelToMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChannelToMarketActionPerformed
        int selectedRow = tblNotAddedChannelToMarket.getSelectedRow();
        if (selectedRow >= 0) {
            Integer channelId = (Integer) tblNotAddedChannelToMarket.getValueAt(selectedRow, 0);
            String channelName = (String) tblNotAddedChannelToMarket.getValueAt(selectedRow, 1);

            DefaultTableModel modelAdded = (DefaultTableModel) tblAddedChannelToMarket.getModel();
            DefaultTableModel modelNotAdded = (DefaultTableModel) tblNotAddedChannelToMarket.getModel();

            // Add to the added channel table
            modelAdded.addRow(new Object[]{channelId, channelName});

            // Remove from the not added channel table
            modelNotAdded.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a channel to add", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddChannelToMarketActionPerformed

    private void btnRemoveChannelFromMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveChannelFromMarketActionPerformed
        int selectedRow = tblAddedChannelToMarket.getSelectedRow();
        if (selectedRow >= 0) {
            Integer channelId = (Integer) tblAddedChannelToMarket.getValueAt(selectedRow, 0);
            String channelName = (String) tblAddedChannelToMarket.getValueAt(selectedRow, 1);

            // Check if the channel is actually part of the market
            if (market.getChannels().contains(channelId)) {
                market.removeChannel(channelId);

                DefaultTableModel modelAdded = (DefaultTableModel) tblAddedChannelToMarket.getModel();
                DefaultTableModel modelNotAdded = (DefaultTableModel) tblNotAddedChannelToMarket.getModel();

                // Remove from the added channel table
                modelAdded.removeRow(selectedRow);

                // Add back to the not added channel table
                modelNotAdded.addRow(new Object[]{channelId, channelName});

                // Save changes to DataManager
                DataManager.marketCatalog.put(market.getId(), market);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a channel to remove", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveChannelFromMarketActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name = txtMarketName.getText().trim();
        String description = txtMarketDecription.getText().trim();

        if (name.isEmpty() || description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name and description cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update market details
        market.setName(name);
        market.setDescription(description);

        // Save channels to the Market object
        DefaultTableModel model = (DefaultTableModel) tblAddedChannelToMarket.getModel();
        Set<Integer> channels = new HashSet<>();
        for (int i = 0; i < model.getRowCount(); i++) {
            Integer channelId = (Integer) model.getValueAt(i, 0);
            channels.add(channelId);
            Channel channel = DataManager.channelDirectory.get(channelId);
            channel.addMarketId(market.getId());
        }
        market.setChannels(channels);

        // Save changes to DataManager
//        DataManager.marketCatalog.put(market.getId(), market);
        JOptionPane.showMessageDialog(this, "Market details saved successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void loadData() {
        // Load market details into text fields
        txtMarketID.setText(String.valueOf(market.getId()));
        txtMarketName.setText(market.getName());
        txtMarketDecription.setText(market.getDescription());

        // Load channels into tables
        DefaultTableModel modelAdded = (DefaultTableModel) tblAddedChannelToMarket.getModel();
        DefaultTableModel modelNotAdded = (DefaultTableModel) tblNotAddedChannelToMarket.getModel();

        modelAdded.setRowCount(0); // Clear existing data
        modelNotAdded.setRowCount(0); // Clear existing data

        // Iterate over all channels
        for (Map.Entry<Integer, Channel> entry : DataManager.channelDirectory.entrySet()) {
            Integer channelId = entry.getKey();
            Channel channel = entry.getValue();

            if (market.getChannels().contains(channelId)) {
                // If the channel is already added to the market
                modelAdded.addRow(new Object[]{channelId, channel.getName()});
            } else {
                // If the channel is not added to the market
                modelNotAdded.addRow(new Object[]{channelId, channel.getName()});
            }
        }
    }


    
    private void loadParentFrame() {
        Point myPosition = getLocation();
        this.parentFrame.setLocation(myPosition);
        this.parentFrame.setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddChannelToMarket;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageMarketBundles;
    private javax.swing.JButton btnRemoveChannelFromMarket;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblAddedChannelToMarket;
    private javax.swing.JTable tblNotAddedChannelToMarket;
    private javax.swing.JTextArea txtMarketDecription;
    private javax.swing.JTextField txtMarketID;
    private javax.swing.JTextField txtMarketName;
    // End of variables declaration//GEN-END:variables
}
