/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.admin;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import model.User;
import ui.AccSecurityJFrame;
import ui.ViewUserDetailsJFrame;
/**
 *
 * @author sourabhkumar
 */
public class AdminPortalJFrame extends javax.swing.JFrame {
    /**
     * Creates new form AdminPortalJFrame
     */
    User u;
    public AdminPortalJFrame(User u) {
        this.u = u;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Set close operation
        initProfessorPortalView();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Calculate the position to be at the lower right corner
        int x = screenSize.width - getWidth();
        int y = screenSize.height - getHeight();
        setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnViewUsers = new javax.swing.JButton();
        btnUserDetails = new javax.swing.JButton();
        btnCourseManage = new javax.swing.JButton();
        btnAccSecurity = new javax.swing.JButton();
        lblPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Admin Portal");

        btnViewUsers.setText("View Users");
        btnViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUsersActionPerformed(evt);
            }
        });

        btnUserDetails.setText("User Details");
        btnUserDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDetailsActionPerformed(evt);
            }
        });

        btnCourseManage.setText("Course Management");
        btnCourseManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseManageActionPerformed(evt);
            }
        });

        btnAccSecurity.setText("Account Security");
        btnAccSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccSecurityActionPerformed(evt);
            }
        });

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setText("No Pic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCourseManage))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAccSecurity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAccSecurity, btnCourseManage, btnUserDetails, btnViewUsers});
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewUsers)
                    .addComponent(btnUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccSecurity)
                    .addComponent(btnCourseManage))
                .addGap(118, 118, 118))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAccSecurity, btnCourseManage, btnUserDetails, btnViewUsers});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDetailsActionPerformed
        // TODO add your handling code here:
        dispose();
        ViewUserDetailsJFrame viewUserDetail = new ViewUserDetailsJFrame(this.u);
        viewUserDetail.setVisible(true);
    }//GEN-LAST:event_btnUserDetailsActionPerformed

    private void btnAccSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccSecurityActionPerformed
        // TODO add your handling code here:
        dispose();
        AccSecurityJFrame accSec = new AccSecurityJFrame(this.u);
        accSec.setVisible(true);
    }//GEN-LAST:event_btnAccSecurityActionPerformed

    private void btnViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUsersActionPerformed
        // TODO add your handling code here:
        dispose(); 
        ListUserJFrame listUserFrame = new ListUserJFrame(u);
        listUserFrame.setVisible(true);
    }//GEN-LAST:event_btnViewUsersActionPerformed

    private void btnCourseManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseManageActionPerformed
        // TODO add your handling code here:
        dispose(); 
        ListCourseJFrame listCourseFrame = new ListCourseJFrame(u);
        listCourseFrame.setVisible(true);
    }//GEN-LAST:event_btnCourseManageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccSecurity;
    private javax.swing.JButton btnCourseManage;
    private javax.swing.JButton btnUserDetails;
    private javax.swing.JButton btnViewUsers;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
    private void initProfessorPortalView() {
        ImageIcon imageIcon;
        String picPath = u.getPicPath();

        if (picPath != null && !picPath.isEmpty()) {
            // Load the provided picture
            try {
                imageIcon = new ImageIcon(picPath);
            } catch (Exception ex) {
                imageIcon = null; // Handle image loading error
            }
        } else {
            if (u.getGender() == null) {
                imageIcon = new ImageIcon("data/images/no_pic.jpeg");
            } else             // Load a default image based on gender
                imageIcon = switch (u.getGender()) {
                case "Female" -> new ImageIcon("data/images/no_pic_female.jpeg");
                case "Male" -> new ImageIcon("data/images/no_pic_male.jpeg");
                default -> new ImageIcon("data/images/no_pic.jpeg");
            };
        } 
        if (imageIcon != null) {
            Image image = imageIcon.getImage();
            int labelWidth = lblPicture.getWidth();
            int labelHeight = lblPicture.getHeight();
            double scaleX = (double) labelWidth / image.getWidth(null);
            double scaleY = (double) labelHeight / image.getHeight(null);
            Image scaledImage = image.getScaledInstance((int) (image.getWidth(null) * scaleX), (int) (image.getHeight(null) * scaleY), Image.SCALE_SMOOTH);
            ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
            lblPicture.setText(null);
            lblPicture.setIcon(scaledImageIcon);
        } else {
            // Handle the case where an image couldn't be loaded
            lblPicture.setIcon(null);
        }
    }
}
